accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth import views as auth_views


urlpatterns = [
	url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lists import views

urlpatterns = [
	url(r'^new$', views.new_quote, name='new_quote'),
	url(r'^(\d+)/$', views.view_quote, name='view_quote'), #(\d+) captures any digits passed between /.../ and assigns it to an extra param passed to the view function (which we named author_id in views.py)
    #url(r'^admin/', include(admin.site.urls)),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as quote_views
from lists import urls as quote_urls
from accounts import urls as account_urls

urlpatterns = [
	url(r'^$', quote_views.home_page, name='home'),
	url(r'^quotes/', include(quote_urls)),
	url(r'^accounts/', include(account_urls)),
    #url(r'^admin/', include(admin.site.urls)),
]

accounts/models.py
from django.db import models
import uuid
from django.contrib import auth

auth.signals.user_logged_in.disconnect(auth.models.update_last_login) #updates the last_login property; without this, django errors out that this field does not exist.

class User(models.Model):
	email = models.EmailField(primary_key=True)
	REQUIRED_FIELDS = ()
	USERNAME_FIELD = 'email'

	is_anonymous = False
	is_authenticated = True

class Token(models.Model):
	email = models.EmailField()
	uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Author(models.Model):
	
	def get_absolute_url(self):
		return reverse('view_quote', args=[self.id])

class Quote(models.Model):
	text = models.TextField(default='')
	author = models.ForeignKey(Author, default=None)

	def __str__(self):
		return self.text

	class Meta:
		ordering = ('id',)
		unique_together = ('author', 'text') #ensure duplicate quotes for the same author cannot be saved to the DB

lists/forms.py
from django import forms
from lists.models import Quote
from django.core.exceptions import ValidationError

EMPTY_QUOTE_ERROR = "You can't submit a quote with no text!"
DUPLICATE_QUOTE_ERROR = "This quote already exists."

class QuoteForm(forms.models.ModelForm):

	class Meta:
		model = Quote
		fields = ('text',)
		widgets = {
			'text': forms.fields.TextInput(attrs={
				'placeholder': 'Enter a new quote',
				'class': 'form-control input-lg'
			})
		}
		error_messages = {
			'text': {'required': EMPTY_QUOTE_ERROR}
		}

	def save(self, for_author):
		self.instance.author = for_author #.instance is the db object that is currently being modified or created
		return super().save()

class ExistingAuthorQuoteForm(QuoteForm):
	
	def __init__(self, for_author, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.instance.author = for_author #link the object currently being modified to the author

	def validate_unique(self):
		try:
			self.instance.validate_unique()
		except ValidationError as e:
			e.error_dict = {'text': [DUPLICATE_QUOTE_ERROR]}
			self._update_errors(e)

	def save(self):
		return forms.models.ModelForm.save(self) #call the grandparent class save method (with no for_author, since this is already taken care of in init)

accounts/views.py
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.contrib import auth, messages
from accounts.models import Token
from django.core.urlresolvers import reverse

# Create your views here.
def send_login_email(request):
	email = request.POST['email']
	token = Token.objects.create(email=email)
	url = request.build_absolute_uri(
		reverse('login') + '?token={uid}'.format(uid=str(token.uid))
	)
	message_body = 'Use this link to log in:\n\n{url}'.format(url=url)
	send_mail('Your login link for Wise Words', message_body, 'noreply@wisewords', [email], fail_silently=False)
	messages.success(request, "Check your email.  We've sent you a link to log in.")
	return redirect('/')

def login(request):
	user = auth.authenticate(uid=request.GET.get('token'))
	if user:
		auth.login(request, user)
	return redirect('/')

# def logout(request):
# 	auth.logout(request)
# 	return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from lists.models import Quote, Author
from lists.forms import QuoteForm, ExistingAuthorQuoteForm

# Create your views here.
def home_page(request):
	return render(request, 'home.html', {'form': QuoteForm()})

def view_quote(request, author_id):
	author = Author.objects.get(id=author_id) #retrieve the author using the id passed in as part of the URL
	form = ExistingAuthorQuoteForm(for_author=author)
	if request.method == 'POST':
		form = ExistingAuthorQuoteForm(for_author=author, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect(author) #gets '/quotes/%d/' % (author.id) using the get_absolute_url fn in the Author model
	return render(request, 'quotes.html', {'author': author, 'form': form})

def new_quote(request):
	form = QuoteForm(data=request.POST)
	if form.is_valid():
		author = Author.objects.create()
		form.save(for_author=author)
		return redirect(author) #gets '/quotes/%d/' % (author.id) using the get_absolute_url fn in the Author model
	else:
		return render(request, 'home.html', {'form': form})

lists/templates/base.html
<! DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	    <link href="/static/base.css" rel="stylesheet">
		<title>Wise Words</title>
	</head>
	<body>
		<div class="container">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container-fluid">
					<a class="navbar-brand" href="/">Wise Words</a>
					{% if user.email %}
						<ul class="nav navbar-nav navbar-right">
							<li class="navbar-text">Logged in as {{ user.email }}</li>
							<li><a href="{% url 'logout' %}">Log out</a></li>
						</ul>
					{% else %}
						<form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
							<span>Enter email to log in:</span>
							<input class="form-control" name="email" type="text"></input>
							{% csrf_token %}
						</form>
					{% endif %}
					
				</div>
			</nav>

			{% if messages %}
				<div class="row">
					<div class="col-md-8">
						{% for message in messages %}
							{% if messages.tags == 'success' %}
								<div class="alert alert-success">{{ message }}</div>
							{% else %}
								<div class="alert alert-warning">{{ message }}</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			{% endif %}
			
			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							{{ form.text }}	
							{% csrf_token %}
							{% if form.errors %}
								<div class="form-group has-error">
									<span class="help-block">{{ form.text.errors }}</span>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>

			
		</div>

		<script src="/static/jquery-3.1.1.min.js"></script>
		<script src="/static/list.js"></script>

		<script>
			$(document).ready( function() {
				window.Superlists.initialize();
			});
			
		</script>

	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Wise Words{% endblock %}
{% block form_action %}{% url 'new_quote' %}{% endblock %}

lists/templates/quotes.html
{% extends 'base.html' %}

{% block header_text %}Wise words{% endblock %}
{% block form_action %}{% url 'view_quote' author.id %}{% endblock %}

{%block table %}
	<table id="id_quote_table" class="table">
		{% for quote in author.quote_set.all %}
			<tr><td>{{ quote.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}